CREATE TABLE USER_INFO 
(
  USER_ID NUMBER(5, 0) 
, USER_NAME VARCHAR2(20 BYTE) 
, USER_EMAIL VARCHAR2(20 BYTE) 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

COMMENT ON COLUMN USER_INFO.USER_ID IS '저장된순서';

COMMENT ON COLUMN USER_INFO.USER_NAME IS '유저이름';
