//취미테이블 생성
DROP TABLE Hobbies;
//NUMBER : 소수점 이하자리까지 OK
//INT : 소수점 이하는 저장X (정수형 데이터만 ㅇㅋ)
CREATE TABLE Hobbies (
    MNO INT PRIMARY KEY,
    Hobby VARCHAR2(100)
);

/*멤버들의 취미 데이터 삽입
INSERT INTO Hobbies (MNO, Hobby)
    VALUES (1, '독서');
이렇게 30명이 다 되는 멤버의 데이터를 일일이 추가할 것인가? 으
SELECT를 사용하자!
*/

//DUAL 어쩌구 UNION ALL 2개이상..?
INSERT INTO Hobbies (MNO, Hobby)
SELECT 1, '책읽기' FROM DUAL UNION ALL
SELECT 2, '수영' FROM DUAL UNION ALL
SELECT 3, '독서' FROM DUAL UNION ALL
SELECT 4, '코딩' FROM DUAL UNION ALL
SELECT 5, '여행' FROM DUAL UNION ALL
SELECT 6, '블로그' FROM DUAL UNION ALL
SELECT 7, '코테' FROM DUAL UNION ALL
SELECT 8, '쇼핑' FROM DUAL UNION ALL
SELECT 9, '춤추기' FROM DUAL UNION ALL
SELECT 10, '하이킹' FROM DUAL UNION ALL
SELECT 11, '등산' FROM DUAL UNION ALL
SELECT 12, '격투기' FROM DUAL UNION ALL
SELECT 13, '게임' FROM DUAL UNION ALL
SELECT 14, '스포츠관람' FROM DUAL UNION ALL
SELECT 15, '축구' FROM DUAL UNION ALL
SELECT 16, '요가' FROM DUAL UNION ALL
SELECT 17, '낚시' FROM DUAL UNION ALL
SELECT 18, '쇼핑' FROM DUAL UNION ALL
SELECT 19, '테니스' FROM DUAL UNION ALL
SELECT 20, '골프' FROM DUAL UNION ALL
SELECT 21, '여행' FROM DUAL; //마지막 데이터는 ALL할게 없어서 걍 DUAL하고 세미콜론으로 끝낸다

GRANT DBA TO khstore;